### ISSUE TITLE
Chapter 4: Panic when the JSON response doesn't have noun/verb field

### ISSUE THREAD

**Issue by anarchyrucks** [matryer/goblueprints#45]
Panic is caused in bighuge.go file when the JSON response does not have either noun or verb field.
Example: ant, anarchy etc.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11fa5cb]

goroutine 1 [running]:
anarchyrucks/thesaurus.(*BigHuge).Synonyms(0xc420049ec8, 0xc420049e28, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/anarchyrucks/go/src/anarchyrucks/thesaurus/bighuge.go:36 +0x3fb
main.main()
	/Users/anarchyrucks/go/src/anarchyrucks/synonyms/main.go:18 +0x159
```

**Comment by matryer** [comment]
Yes this was fixed in the 2nd edition. You can be a little defensive in the code to catch those cases. 

See the code in this repo for an example.

**Comment by anarchyrucks** [comment]
Thanks.
